### ISSUE TITLE
Unexpected timeout with Tokio v0.2.0 refactor + threaded scheduler

### ISSUE THREAD

**Issue by carllerche** [djc/quinn#532] opened 2019-11-28 07:09 UTC
I was playing around w/ the quinn bench on Tokio 0.2.0 (sha `b90bc38c5d146d3c7169f3316453a60b21f93ee3`). I modified it to use the threaded scheduler: https://gist.github.com/carllerche/9de58fe76dd9fac1be6502b930dcc812#file-quinn-threaded-rs

When running on my local box (macbook pro) in release mode, I **sometimes** get the following panic:

```
thread 'tokio-runtime-worker' panicked at 'server conn driver: TimedOut', src/libcore/result.rs:1165:5
stack backtrace:
   0: std::sys_common::at_exit_imp::push
   1: core::fmt::ArgumentV1::show_usize
   2: std::io::Write::write_fmt
   3: std::panicking::default_hook::{{closure}}
   4: std::panicking::default_hook
   5: <std::panicking::begin_panic::PanicPayload<A> as core::panic::BoxMeUp>::get
   6: std::panicking::continue_panic_fmt
   7: std::panicking::try::do_call
   8: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
   9: core::result::unwrap_failed
             at src/libcore/result.rs:1165
  10: core::result::Result<T,E>::expect
             at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/libcore/result.rs:960
  11: bulk::run_server::{{closure}}::{{closure}}
             at bench/src/bulk.rs:60
  12: <std::future::GenFuture<T> as core::future::future::Future>::poll::{{closure}}
             at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/libstd/future.rs:43
  13: std::future::set_task_context
             at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/libstd/future.rs:79
  14: <std::future::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/libstd/future.rs:43
  15: tokio::task::core::Core<T>::poll
             at /Users/carllerche/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.1/src/task/core.rs:128
  16: tokio::task::harness::Harness<T,S>::poll::{{closure}}::{{closure}}
             at /Users/carllerche/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.1/src/task/harness.rs:120
  17: core::ops::function::FnOnce::call_once
             at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/libcore/ops/function.rs:227
  18: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/libstd/panic.rs:315
  19: std::panicking::try::do_call
             at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/libstd/panicking.rs:292
  20: panic_unwind::dwarf::eh::read_encoded_pointer
  21: std::panicking::try
             at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/libstd/panicking.rs:271
  22: std::panic::catch_unwind
             at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/libstd/panic.rs:394
  23: tokio::task::harness::Harness<T,S>::poll::{{closure}}
             at /Users/carllerche/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.1/src/task/harness.rs:101
  24: tokio::loom::std::causal_cell::CausalCell<T>::with_mut
             at /Users/carllerche/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.1/src/loom/std/causal_cell.rs:41
  25: tokio::task::harness::Harness<T,S>::poll
             at /Users/carllerche/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.1/src/task/harness.rs:100
  26: tokio::runtime::thread_pool::worker::GenerationGuard::run_task
  27: tokio::runtime::thread_pool::worker::GenerationGuard::run
  28: std::thread::local::LocalKey<T>::with
  29: std::thread::local::LocalKey<T>::with
  30: tokio::runtime::thread_pool::worker::Worker::run
  31: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
  32: std::panicking::try::do_call
  33: panic_unwind::dwarf::eh::read_encoded_pointer
  34: tokio::task::harness::Harness<T,S>::poll
  35: tokio::runtime::blocking::pool::Inner::run2
  36: tokio::runtime::spawner::Spawner::enter
  37: tokio::runtime::time::variant::with_default
  38: tokio::runtime::blocking::pool::Inner::run
```

Running in debug mode, it works fine:

```
recvd 1073741824 bytes in 72.200229681s
sent 1073741824 bytes in 72.201786918s
```

**Comment by daxpedda** [comment] 2019-11-30 02:19
Couldn't reproduce, works perfectly fine for me.

**Comment by djc** [comment] 2019-12-02 10:14
I'm seeing panics in the datagram benchmarks on master before and after the upgrade to tokio-0.2 final on my laptop.

**Comment by daxpedda** [comment] 2019-12-02 10:26
Same. But I think OP was talking specifically about the `bulk` benchmark here, which isn't panicking for me.

**Comment by djc** [comment] 2019-12-02 13:35
Right, `bulk` doesn't panic for me, either.

**Comment by DemiMarie-parity** [comment] 2020-01-13 16:04
My libp2p-quic code occasionally hits a similar problem

**Comment by Ralith** [comment] 2020-04-03 01:04
Does this still reproduce on master? We've had a number of significant bugfixes lately.

**Comment by Ralith** [comment] 2020-06-20 03:21
Closing since this seems to be fixed; feel free to reopen if it can be reproduced.

**Closed by Ralith** 2020-06-20 03:21 UTC

**Comment by ArtBlnd** [comment] 2020-06-25 02:31
I got same issue on my repository. connection just timed out after established.

**Comment by Ralith** [comment] 2020-06-25 02:42
Please open a new issue with details, including specific code and ideally a working repro.

**Comment by ArtBlnd** [comment] 2020-06-25 02:51
https://github.com/aspear-internet/fibers-rs just an PoC project, 

https://github.com/aspear-internet/fibers-rs/blob/fdc8369b77393a42614fa8346f744903b48cb06f/src/fibers-core/lib.rs#L153-L156

Timed out at here.

**Comment by Ralith** [comment] 2020-06-25 03:01
Timing out while waiting the peer to open a stream most likely indicates that your peer was not attempting to open a stream. If you're confident that your peer was, in fact, trying to open a stream, please open a new issue with details and steps to reproduce.

**Comment by ArtBlnd** [comment] 2020-06-25 03:06
I'm sure its opend, client has been emitted some payload after opening streams. but server does not indicates it.

**Comment by Ralith** [comment] 2020-06-25 03:18
Thank you for confirming. Please open a new issue with details and steps to reproduce.
