### ISSUE TITLE
Intermittent timeout with git master

### ISSUE THREAD

**Issue by DemiMarie-parity** [djc/quinn#689] opened 2020-03-17 15:44 UTC
Logs at https://gist.github.com/DemiMarie-parity/c83746d3f95f94861a446207f58e0752

**Comment by Ralith** [comment] 2020-03-17 16:45
I don't see any timeouts in those logs. Can you elaborate?

**Comment by DemiMarie-parity** [comment] 2020-03-17 21:06
This log should have some timeouts: [gist.txt.gz](https://github.com/djc/quinn/files/4345828/gist.txt.gz).

**Comment by Ralith** [comment] 2020-03-17 22:15
It's difficult to analyze these usefully without some way to distinguish logs from the different connections. Can you add a tracing span that identifies the connection around calls into quinn-proto, in particular `handle_timeout` and `handle_event`?

**Comment by DemiMarie-parity** [comment] 2020-03-17 23:27
There is only ever one connection at any given time, which is why I added the span around the entire test, but I can do that.

**Comment by Ralith** [comment] 2020-03-18 00:05
There's no such span in the logs. Did you remember to `enter` it, and hold the guard until after the calls are complete?

There should be at least two `Connection`s; the client and the server.

**Comment by DemiMarie-parity** [comment] 2020-03-18 00:35
Here is the relevant code:

```rust
[end.gz](https://github.com/djc/quinn/files/4346377/end.gz)
[end.gz](https://github.com/djc/quinn/files/4346380/end.gz)


#[test]
fn communicating_between_dialer_and_listener() {
    use tracing::info_span;
    init();
    for i in 0..1000u32 {
        let span = info_span!("test", id = i);
        let _guard = span.enter();
        do_test()
    }
}
```

And my command line is

    RUST_LOG=quinn_proto=trace,libp2p_quic=trace,tests=trace,rustls=trace cargo test -plibp2p-quic --release

**Comment by Ralith** [comment] 2020-03-18 00:43
That span does not arise in the logs. Are you perhaps spawning futures inside `do_test`? Spans do not automatically attach themselves to spawned futures. Please also arrange spans that allow the client and server connections to be distinguished; this makes it much easier to inspect the logs.

> I don’t believe that failing to decrypt a single packet should cause a reset to be sent.

It does not. Stateless resets are sent when a packet does not match any known connection. Decryption is only attempted after a packet is successfully matched to a connection.

**Comment by DemiMarie-parity** [comment] 2020-03-18 19:43
> That span does not arise in the logs. Are you perhaps spawning futures inside `do_test`? Spans do not automatically attach themselves to spawned futures. Please also arrange spans that allow the client and server connections to be distinguished; this makes it much easier to inspect the logs.

Indeed `do_test` does spawn futures. Thanks for the suggestion!

> > I don’t believe that failing to decrypt a single packet should cause a reset to be sent.
> 
> It does not. Stateless resets are sent when a packet does not match any known connection. Decryption is only attempted after a packet is successfully matched to a connection.

That makes sense, although the “unable to decrypt” message is rather confusing.

In this case, I think the bug is that a stateless reset tears a connection down that it really shouldn’t.

**Comment by Ralith** [comment] 2020-03-18 22:27
The tracing-futures crate can be used to attach spans to ("instrument")
futures.

A stateless reset will not be detected for a connection unless it was
generated for that connection's ID, which is guaranteed by cryptographic
mechanisms. That only occurs if the peer doesn't recognize the connection,
in which case it's there's no other possible recourse than notifying the
application; think of it as a fast path for a timeout. This can occur when
the packets that indicate that the peer is closing the connection are lost,
and the peer ultimately gives up and discards state.

**Comment by DemiMarie-parity** [comment] 2020-03-20 18:28
[Here](https://github.com/djc/quinn/files/4361289/log.txt.gz) is a compressed (warning: >10MB uncompressed!) log file that has spans added.

**Comment by DemiMarie-parity** [comment] 2020-03-20 18:33
[Here](https://github.com/djc/quinn/files/4361308/log.txt.gz) is another compressed log file that clearly shows a CONNECTION_ID_LIMIT_ERROR.  Unfortunately, this one doesn’t have spans from my code.

**Comment by DemiMarie-parity** [comment] 2020-03-20 18:54
Worth noting that this problem *does not* happen with 0.6.0 (latest released version).

**Comment by DemiMarie-parity** [comment] 2020-03-20 19:04
[Here is one log file](https://github.com/djc/quinn/files/4361421/log.txt.gz), and 
[here is another one with a really bad network](https://github.com/djc/quinn/files/4361422/log.txt.gz)

**Comment by djc** [comment] 2020-03-20 19:23
So can you bisect to find the regressing commit?

**Comment by DemiMarie-parity** [comment] 2020-03-20 19:27
> So can you bisect to find the regressing commit?

I can try!  I do get a timeout on 0.6.0, but only with a really really really bad network (I think it was 80+% packet loss or similar).

**Comment by DemiMarie-parity** [comment] 2020-03-20 19:27
I ran
```
sudo tc qdisc change dev lo root netem delay 5ms 10ms 90% distribution normal loss gemodel 40% duplicate 100% corrupt 80% reorder 30% 50%
```

**Comment by Ralith** [comment] 2020-03-21 03:14
> Here is a compressed (warning: >10MB uncompressed!) log file that has spans added.

Thanks! I'm guessing each connection has a distinct UDP port? At first glance the main thing that jumps out at me is the stateless resets at the end; I'm guessing that's the unexpected behavior in this log?

> (I think it was 80+% packet loss or similar).

That's probably a legitimate timeout.

**Comment by DemiMarie-parity** [comment] 2020-03-22 20:39
> Thanks! I'm guessing each connection has a distinct UDP port? At first glance the main thing that jumps out at me is the stateless resets at the end; I'm guessing that's the unexpected behavior in this log?

The UDP ports are randomly assigned by the OS, so I suspect so.  In any case, these are logged.

And yes, the stateless resets are the main unexpected behavior.  I understand if a packet from a previous connection triggered a reset, but that reset packet should then be ignored.

> > (I think it was 80+% packet loss or similar).
> 
> That's probably a legitimate timeout.

Good to know, thanks!

**Comment by DemiMarie-parity** [comment] 2020-03-22 20:50
@djc 0f5b851189b97754b69b6d704b445bca9f77a8e2 should be the first bad commit.  I only checked commits between 0.6.0 and master that changed files in `quinn-proto/`.

**Comment by djc** [comment] 2020-03-22 21:14
That's very interesting, as that commit is supposed to be refactoring-only, that is, the functionality should be unchanged by it.

**Comment by Ralith** [comment] 2020-03-22 21:17
> The stateless resets are unexpected, but I believe there is also a CONNECTION_ID_LIMIT_ERROR somewhere.

There is no such error in that log.

> 0f5b851 should be the first bad commit

To be clear, you see unexpected resets only after that commit? If you're seeing `CONNECTION_ID_LIMIT_ERROR` as well, that's likely a different issue.

**Comment by DemiMarie-parity** [comment] 2020-03-22 21:28
> > The stateless resets are unexpected, but I believe there is also a CONNECTION_ID_LIMIT_ERROR somewhere.
> 
> There is no such error in that log.
> 
> > [0f5b851](https://github.com/djc/quinn/commit/0f5b851189b97754b69b6d704b445bca9f77a8e2) should be the first bad commit
> 
> To be clear, you see unexpected resets only after that commit? If you're seeing `CONNECTION_ID_LIMIT_ERROR` as well, that's likely a different issue.
My tests fail beginning with this commit.  [log.txt.gz](https://github.com/djc/quinn/files/4366386/log.txt.gz) (made with git HEAD) clearly shows a `CONNECTION_ID_LIMIT_ERROR`.

**Comment by DemiMarie-parity** [comment] 2020-03-22 21:33
[This log file](https://github.com/djc/quinn/files/4366394/log.txt.gz) was made with d1885b6302b6f83c153bc9dbac0a51eb37ac3287.  It also shows a `CONNECTION_ID_LIMIT_ERROR`.

**Comment by Ralith** [comment] 2020-03-22 21:35
Thanks! Investigating those now.

**Comment by DemiMarie-parity** [comment] 2020-03-22 21:37
You’re welcome!  @Ralith @djc thank you both for this awesome library.

**Comment by Ralith** [comment] 2020-03-22 23:33
Turns out the unexpected stateless reset and `CONNECTION_ID_LIMIT_ERROR` were indeed the same issue, manifesting nondeterministically in two different ways due to a race condition. Fix is up for review.

**Closed** 2020-03-23 08:26 UTC
