### ISSUE TITLE
Resolving quinn::Incoming

### ISSUE THREAD

**Issue by ustulation** [djc/quinn#293] opened 2019-04-04 13:14 UTC
Is there a way to cleanly resolve `quinn::Incoming` we get from `quinn::EndpointBuilder::bind()` for instance ? I was wondering if it would be good to have a quit/close on `quinn::Endpoint` (something the user potentially holds on to) to exit everything - all `quinn::Connection/IncomingStreams/Incoming/Driver/ConnectionDriver`, all `read_to_end` and `write_all` etc., as at that point the user likely wants a clean exit of the event loop resolving all futures as quickly as possible. Maybe a drop on (last copy of) `Endpoint` could also do it in additional to explicit `close()/quit()/shutdown()`.

**Comment by djc** [comment] 2019-04-04 13:20
So basically you want `EndpointInner::terminate()` analogous to `ConnectionInner::terminate()` that's called on both implicit or explicit closing of the `Endpoint`? That seems reasonable.

**Comment by Ralith** [comment] 2019-04-04 23:20
I don't think dropping the last `Endpoint` handle should do this; it's reasonable for a long-lived server to spawn off an incoming connection handler task and drop everything else. An explicit shutdown method makes sense to me, though, because we can provide one more easily than the user can implement it themselves, and it nicely exposes the option to perform an instant shutdown whereas dropping everything would still wait out the draining periods, which is unnecessary when we're about to close the UDP socket anyway.

**Comment by Ralith** [comment] 2019-04-05 06:37
When I went to implement this, I realized that killing the `Endpoint` instantaneously makes it difficult or impossible to notify peers that any still-active connections are closing, leading to slow timeouts, or worse if the idle timeout isn't enabled. I think it would be better-behaved to instead expose a convenience method for, in effect, broadcasting a `Connection::close` call to all active connections and terminating the `Incoming` stream, allowing the rest of the system to wind down naturally, draining periods included. Does that sound good?

**Comment by ustulation** [comment] 2019-04-05 09:15
That sounds fine - as long as there's a way exposed by the API :)

If you don't mind could you give me some details about the behaviour as user code might eventually depend on some of the intricacies ?

So in case of TCP, for shutdown-write, all the data in the Tx (or re-Tx) buffers are firstly sent followed by the FIN. The socket at this point does not accept any new data. The peer on receiving FIN gets an EOF read telling its user that they should not expect any more reads. The user then calls shutdown-write there which eventually gets the FIN to the former peer which then gets EOF read and everything ends with all pending data (accepted by the TCP buffers) now exchanged.

First by reading this:
https://github.com/djc/quinn/blob/30343cea024c1126e229eca499fb1aab81ce0416/quinn/src/connection.rs#L171
I suppose QUIC has no such specification for shutdowns which is why `quinn` went for immediate closure on calling `close()` (and i guess at that point all pending data with quinn (unack'd or yet to be written) are lost/dropped). First of all is that correct (about QUIC not making this their goal) ?

Then from https://github.com/djc/quinn/issues/293#issuecomment-480164897:
> makes it difficult or impossible to notify peers that any still-active connections are closing,

i deduce that the intention in `quinn` is to send some control data to the peer notifying the shutdown. This control-data could appear out of order w.r.t. data (unlike TCP FIN's) and cause an immediate shutdown of the peer too. This makes sense as QUIC is mutlistreamed unlike TCP so to mimic the behaviour you would probably have to send it after all data in all streams have be delivered which may or may not be desirable (i can't decide at this moment).

However there is also this in the same comment above:
> allowing the rest of the system to wind down naturally, draining periods included.

So I'm a bit confused about this `draining period` if `close()` was intended to be immediate and ungraceful as in the docs. Does this refer to the reliability of the control data that `close()` sends ? i.e., does `quinn` intend on making sure the `close()` is ack'd by the peer or is it fire-and-forget sort of an event. Also is that something to do with the `draining period` ?

PS: I didn't look at the code to try figure all this out - i wanted to know the intention rather than what's currently in the code as those two can sometimes be different (and manifest as a bug in impl). Hence the questions.

**Comment by Ralith** [comment] 2019-04-05 15:31
> If you don't mind could you give me some details about the behaviour as user code might eventually depend on some of the intricacies ?

The QUIC analog of TCP shutdown is the `finish` operation on an outgoing stream, which is what's driven by calling `tokio::io::shutdown` on a stream. It will block until the peer has confirmed receipt of all data on that specific stream.

> First of all is that correct (about QUIC not making this their goal) ?

QUIC leaves it up to the application to decide whether to finish any given stream before closing the connection. In many cases, you no longer care about finishing a stream, so close lets you gracefully clean up without waiting unnecessarily.

> So I'm a bit confused about this draining period if close() was intended to be immediate and ungraceful as in the docs

Close is graceful, but does not ensure delivery of outstanding data because that's left to the application's discretion. During the draining period, we respond to every incoming packet with a new close frame, unless a close frame is previously received from the peer. Additionally, we do not generate stateless resets for packets received during the draining period, reducing the odds of one clobbering the graceful close state on the peer.

As a result, receipt of the close packet by the peer is likely, but not strongly guaranteed. If you need guarantee that the peer receives some information before the connection is closed, send it in a stream and finish that stream before calling close.

**Comment by ustulation** [comment] 2019-04-05 16:19
Ah right, that makes it clear now. Thanks !

Could you tell me what exactly is this "draining period" and what factors influence its interval ?

**Comment by Ralith** [comment] 2019-04-05 16:48
My terminology above was imprecise. The exact semantics are as follows:

When a connection is closed due to application request or an error (other than timeout or stateless reset), it is said to immediately enter the "closing period." The close timer is set for a period of 3 times the [probe timeout (PTO)](https://quicwg.org/base-drafts/draft-ietf-quic-recovery.html#computing-pto). and a close frame is transmitted to the peer. When the close timer expires, all connection state may be discarded; in Quinn's case, this means we can terminate the `ConnectionDriver`.

While in the closing period, receipt of any authenticated packets may prompt a retransmission of the close frame. If a close frame or stateless reset is received from the peer, the connection may then transition into the "draining period", which ends when the closing period would have ended, but involves no further retransmission of the close frame.

**Comment by djc** [comment] 2019-04-05 18:53
@Ralith makes me wonder how hard it would be to expose a method on `Endpoint` and/or `Connection` that does something like "complete all open streams, then close"?

**Comment by Ralith** [comment] 2019-04-06 00:52
That would amount to having `ConnectionDriver` track live streams and finish them on demand, which I think would represent a noticable increase in complexity. I'm skeptical of the benefit; why call `close` if you're not done with whatever you're doing first?

**Comment by djc** [comment] 2019-04-06 20:05
Fair enough.

**Closed** 2019-04-06 20:32 UTC
